### ISSUE TITLE
`npm test` I got an error with no change but on travis is good

### ISSUE THREAD

**Issue by A-312** [mozilla/node-convict#300]
On Windows with `npm test` and no change on my branch I got: 

```
  1) CLI tests
       sensitive_validation:
     Error: done() invoked with non-Error: public: must be a positive integer: value was -1
private: must be a positive integer
      at ChildProcess.<anonymous> (test\cli-tests.js:115:14)
      at emit (internal/child_process.js:820:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
```

And when I PR my branch and check on travis this error doesn't appear.

**Comment by madarche** [comment]
I have no idea 😕

**Comment by A-312** [comment]
`sensitive_validation.out` is the only one file with new line, I think it the new line which make an issue on windows

**Comment by madarche** [comment]
Don't hesitate to remove the new line!
