### ISSUE TITLE
Unable to use the name "properties" within a schema

### ISSUE THREAD

**Issue by arhughes** [mozilla/node-convict#318]
It is not possible to have a schema with an element named "properties".

```
const convict = require('convict');

const config = convict({
  thing: {
    properties: {
      one: {
        default: 1,
        format: 'Number',
      },
      two: {
        default: 2,
        format: 'Number',
      },
    },
  },
});

config.validate();
```

Produces the output:
```
Warning: configuration param 'thing.properties.one' not declared in the schema
configuration param 'thing.properties.two' not declared in the schema
[snip]/convict-test/node_modules/convict/lib/convict.js:679
          throw new Error(output);
          ^

Error: configuration param 'thing.one' missing from config, did you override its parent?
configuration param 'thing.two' missing from config, did you override its parent?
    at Object.validate ([snip]/convict-test/node_modules/convict/lib/convict.js:679:17)
    at Object.<anonymous> ([snip]/convict-test/index.js:18:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```

Renaming `properties` to any other string makes the configuration validate without error..

**Comment by A-312** [comment]
I will make a PR to fix this issue
